apiVersion: v1
kind: Service
metadata:
  labels:
    app: dotnet-weather
  name: dotnet-weather
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8080
      $patch: delete
    - port: 8080
      targetPort: 8080
  selector:
    app: dotnet-weather
