---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: promtail
      version: 6.9.3
  interval: 1m0s
  releaseName: promtail
  targetNamespace: promtail
  values:
    config:
      clients:
      - url: http://loki.loki:3100/loki/api/v1/push
    networkPolicy:
      enabled: false
    serviceMonitor:
      enabled: true
      prometheusRule:
        enabled: true
        rules:
        - alert: PromtailRequestErrors
          annotations:
            description: |
              The {{ $labels.job }} {{ $labels.route }} is experiencing
              {{ printf \"%.2f\" $value }} errors.
              VALUE = {{ $value }}
              LABELS = {{ $labels }}
            summary: Promtail request errors (instance {{ $labels.instance }})
          expr: 100 * sum(rate(promtail_request_duration_seconds_count{status_code=~"5..|failed"}[1m]))
            by (namespace, job, route, instance) / sum(rate(promtail_request_duration_seconds_count[1m]))
            by (namespace, job, route, instance) > 10
          for: 5m
          labels:
            severity: critical
        - alert: PromtailRequestLatency
          annotations:
            description: |
              The {{ $labels.job }} {{ $labels.route }} is experiencing
              {{ printf \"%.2f\" $value }}s 99th percentile latency.
              VALUE = {{ $value }}
              LABELS = {{ $labels }}
            summary: Promtail request latency (instance {{ $labels.instance }})
          expr: histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[5m]))
            by (le)) > 1
          for: 5m
          labels:
            severity: critical
    sidecar:
      configReloader:
        enabled: true
        servicemonitor:
          enabled: true

