---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  chart:
    spec:
      chart: promtail
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: promtail
      version: 6.11.3
  interval: 1m0s
  releaseName: promtail
  targetNamespace: promtail
  values:
    config:
      clients:
      - url: http://loki.loki:3100/loki/api/v1/push
    networkPolicy:
      enabled: false
    serviceMonitor:
      enabled: true
      prometheusRule:
        enabled: false
    sidecar:
      configReloader:
        enabled: true
        servicemonitor:
          enabled: true
