apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- db-config.yaml
- db-service.yaml
- dotnet-weather-config.yaml
- dotnet-weather-service.yaml