apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: podinfo
    namespace: flux-system
  policy:
    semver:      
      # range: '5.2.x'
      # range: '>=6.0.0'
      range: '6.2.2'