---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
  namespace: flux-system
spec:
  chart:
    spec:
      chart: falco
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
  interval: 10m0s

