---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flagger
  namespace: flux-system
spec:
  dependsOn:
  - name: linkerd
  healthChecks:
  - kind: Deployment
    name: flagger
    namespace: linkerd
  interval: 1m0s
  path: ./infrastructure/flagger
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-linkerd
  timeout: 2m0s

