---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keda
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kedacore
  interval: 10m0s

