---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kubernetes-event-exporter
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-event-exporter
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kubernetes-event-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubernetes-event-exporter
      version: 2.4.2
  interval: 1m0s
  releaseName: kubernetes-event-exporter
  targetNamespace: kubernetes-event-exporter
  values:
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: true
