apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo-kustomization.yaml
  - podinfo-source.yaml
  - podinfo-registry.yaml
  - podinfo-policy.yaml
  - podinfo-monitor.yaml
