apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

resources:
  # you can also specify a Git repo URL here
  - ../../base/
  - hoverfly-deployment.yaml
  - hoverfly-service.yaml
  - database-deployment.yaml
  - database-service.yaml

configMapGenerator:
  - name: database-configmap
    behavior: merge
    literals:
      - POSTGRES_HOST=weather-database
      - POSTGRES_DB=weather

secretGenerator:
  - name: database-secrets
    behavior: merge
    literals:
      - POSTGRES_PASSWORD=1qay2wsx
      - POSTGRES_USER=payara
