---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: 2.9.0
  interval: 1m0s
  releaseName: sealed-secrets
  targetNamespace: sealed-secrets
  values:
    ingress:
      enabled: true
      hostname: sealed-secrets.ck3.cluster.qaware.de
      ingressClassName: nginx
    metrics:
      dashboards:
        create: true
        labels:
          grafana_dashboard: "1"
      serviceMonitor:
        enabled: true
    networkPolicy:
      enabled: false
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
