---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./applications/bare/talos-cloudkoffer-v3
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

