apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: ${machine_deployment_id}
  namespace: org-${organization}
spec:
  template:
    spec:
      infrastructureRef:
        apiVersion: infrastructure.giantswarm.io/v1alpha3
