apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: ${cluster_id}
  namespace: org-${organization}
spec:
  controlPlaneEndpoint:
    host: api.${cluster_id}.k8s.gorilla.eu-central-1.aws.gigantic.io
    port: 443
  infrastructureRef:
    apiVersion: infrastructure.giantswarm.io/v1alpha3
