---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tempo
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tempo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tempo
      version: 1.3.1
  interval: 1m0s
  releaseName: tempo
  targetNamespace: tempo
  values:
    tempo:
      persistence:
        enabled: false
      reportingEnabled: false
      serviceMonitor:
        enabled: true
