---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      version: v1.12.1
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    extraArgs:
      - --dns01-recursive-nameservers=8.8.8.8:53,8.8.4.4:53
      - --dns01-recursive-nameservers-only=true
    installCRDs: true
    prometheus:
      servicemonitor:
        enabled: true
    webhook:
      networkPolicy:
        enabled: false
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
