---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: goldilocks
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://charts.fairwinds.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: flux-system
spec:
  chart:
    spec:
      chart: goldilocks
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: goldilocks
      version: 6.7.0
  interval: 1m0s
  releaseName: goldilocks
  targetNamespace: goldilocks
  values:
    dashboard:
      ingress:
        enabled: true
        hosts:
        - host: goldilocks.ck3.cluster.qaware.de
          paths:
          - path: /
            type: ImplementationSpecific
        ingressClassName: nginx
      replicaCount: 1
