---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus-stack
  interval: 1h0m0s
  path: ./manifests/monitoring/loki-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-monitoring
  timeout: 5m0s
  wait: true

