---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/external-dns

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  timeout: 2m
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: 1.12.1
  interval: 1m0s
  releaseName: external-dns
  targetNamespace: external-dns
  values:
    domainFilters:
    - cluster.qaware.de
    google:
      project: engineering-cloud
      serviceAccountKey: credentials.json
      serviceAccountSecret: gcp-service-account
    policy: sync
    provider: google
    serviceMonitor:
      enabled: true
    sources:
    - service
    txtOwnerId: ck3-cluster-qaware-de

