---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-dns
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
      version: 1.13.0
  interval: 1m0s
  releaseName: external-dns
  targetNamespace: external-dns
  values:
    domainFilters:
    - cluster.qaware.de
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /etc/secrets/service-account/credentials.json
    extraArgs:
    - --google-project=engineering-cloud
    extraVolumeMounts:
    - mountPath: /etc/secrets/service-account/
      name: secrets
    extraVolumes:
    - name: secrets
      secret:
        secretName: google-application-credentials
    policy: sync
    priorityClassName: ""
    provider: google
    serviceMonitor:
      enabled: true
    sources:
    - service
    txtOwnerId: ck3-cluster-qaware-de
