apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: 1.11.0
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: connectivity
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
