---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kyverno.github.io/kyverno/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kyverno
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kyverno
      version: v3.0.1
  interval: 1m0s
  releaseName: kyverno
  targetNamespace: kyverno
  values:
    admissionController:
      serviceMonitor:
        enabled: true
    backgroundController:
      serviceMonitor:
        enabled: true
    cleanupController:
      serviceMonitor:
        enabled: true
    config:
      enableDefaultRegistryMutation: false
    crds:
      install: true
    grafana:
      enabled: true
    networkPolicy:
      enabled: false
    reportsController:
      serviceMonitor:
        enabled: true
