---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
  - name: prometheus-operator-crds
  interval: 5m0s
  path: ./infrastructure/bare/talos-cloudkoffer-v3/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

