---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
  - name: prometheus-operator-crds
  interval: 5m0s
  path: ./infrastructure/bare/talos-cloudkoffer-v3/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
