---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  dependsOn:
  - name: prometheus-operator-crds
  interval: 5m0s
  path: ./infrastructure/bare/talos-cloudkoffer-v3/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
