---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/bare/talos-cloudkoffer-v3/prometheus-operator-crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
