---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vertical-pod-autoscaler
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/bare/talos-cloudkoffer-v3/vertical-pod-autoscaler
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
