version: '3.4'

services:
  sqldata:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
    ports:
      - "${DB_LOCAL_PORT}:1433"

  dotnet-weather:
    ports:
      - "${APP_LOCAL_PORT}:8080"