version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - SA_PASSWORD=${DB_SA_PASSWORD}
    ports:
      - "${DB_LOCAL_PORT}:1433"
    networks:
      - weather-network

  dotnet-weather:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: dotnet-weather
    ports:
      - "${APP_LOCAL_PORT}:8080"
    depends_on:
      - sqldata
    networks:
      - weather-network

networks:
    weather-network: