version_settings(constraint='>=0.22.2')

docker_build(
    'dotnet-weather',
    '.',
    dockerfile='Dockerfile'
)

k8s_yaml(['k8s/db-config.yaml', 'k8s/db-deployment.yaml', 'k8s/db-service.yaml'])

k8s_yaml(['k8s/dotnet-weather-config.yaml', 'k8s/dotnet-weather-deployment.yaml', 'k8s/dotnet-weather-service.yaml'])

# k8s_resource('dotnet-weather', port_forwards='8080:8080')
# port is already exposed by the app
