apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnet-weather
  name: dotnet-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-weather
  template:
    metadata:
      labels:
        app: dotnet-weather
    spec:
      containers:
        - image: dotnet-weather
          imagePullPolicy: Never
          name: dotnet-weather
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
