apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqldata
  name: sqldata
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    app: sqldata
status:
  loadBalancer: {}
