# -*- mode: Python -*-

local_resource('weather-service-build', './mvnw package -DskipTests', dir='.', deps=['./pom.xml', './src/'], labels=['Java EE'])
docker_build('weather-service', '.', dockerfile='Dockerfile', only=['./target/'])

k8s_yaml(kustomize('./k8s/overlays/dev/'))
k8s_resource(workload='weather-service', port_forwards=[port_forward(18080, 8080, 'HTTP API')], labels=['Java EE'])
