---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: 4.7.0
  interval: 1m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  values:
    controller:
      admissionWebhooks:
        networkPolicyEnabled: false
      extraArgs:
        default-ssl-certificate: cert-manager/wildcard-certificate
      ingressClassResource:
        default: true
      metrics:
        enabled: true
        prometheusRule:
          enabled: true
          rules:
          - alert: NGINXConfigFailed
            annotations:
              description: bad ingress config - nginx config test failed
              summary: uninstall the latest ingress changes to allow config reloads
                to resume
            expr: count(nginx_ingress_controller_config_last_reload_successful ==
              0) > 0
            for: 1s
            labels:
              severity: critical
          - alert: NGINXCertificateExpiry
            annotations:
              description: ssl certificate(s) will expire in less then a week
              summary: renew expiring certificates to avoid downtime
            expr: (avg(nginx_ingress_controller_ssl_expire_time_seconds) by (host)
              - time()) < 604800
            for: 1s
            labels:
              severity: critical
          - alert: NGINXTooMany500s
            annotations:
              description: Too many 5XXs
              summary: More than 5% of all requests returned 5XX, this requires your
                attention
            expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"5.+"} )
              / sum(nginx_ingress_controller_requests) ) > 5
            for: 1m
            labels:
              severity: warning
          - alert: NGINXTooMany400s
            annotations:
              description: Too many 4XXs
              summary: More than 5% of all requests returned 4XX, this requires your
                attention
            expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"4.+"} )
              / sum(nginx_ingress_controller_requests) ) > 5
            for: 1m
            labels:
              severity: warning
        serviceMonitor:
          enabled: true
      service:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: '*.ck3.cluster.qaware.de'
        enableHttp: false
        enableHttps: true
        loadBalancerIP: 192.168.1.102
