apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: cloud-native-weather-vue3
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cloud-native-weather-vue3
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
      # range: '1.0.x'