apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cloud-native-explab
  region: eu-central-1
  version: '1.22'

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  - metadata:
      name: build-service
      namespace: ci-cd
    wellKnownPolicies:
      imageBuilder: true

vpc:
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

managedNodeGroups:
  - name: managed-explab-cluster-ng-1
    instanceType: t3.xlarge
    minSize: 5
    maxSize: 10
    desiredCapacity: 5
    volumeSize: 20
    ssh:
      allow: false
    labels: {role: worker}
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        certManager: true
        albIngress: true
        awsLoadBalancerController: true
        imageBuilder: true
        autoScaler: true        
        ebs: true
        efs: true
        cloudWatch: true