apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 4.4.0
      values:
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: "filesystem"
  interval: 1m0s
  releaseName: loki
  targetNamespace: observability
