name: Test Dotnet Weather

on:
  push:
    paths:
      - 'applications/DotnetWeather/**'
      - '.github/workflows/dotnet-weather.yml'
  workflow_dispatch:

jobs:
  test:
    name: Perform the tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./applications/DotnetWeather

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  push_to_registry:
    name: Push Docker image to Github Container registry
    runs-on: ubuntu-latest
#    needs: test
    defaults:
      run:
        working-directory: ./applications/DotnetWeather

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker-compose build
    - name: Check image
      run: docker images
    - name: Setup node # https://docs.github.com/en/packages/quickstart
      uses: actions/setup-node@v3
      with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
    - run: npm ci
    - run: npm test
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}