name: Test Dotnet Weather

on:
  push:
    paths:
      - 'applications/DotnetWeather/**'
  workflow_dispatch:

jobs:
  Test:
    name: Perform the tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./applications/DotnetWeather

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
