name: Test Dotnet Weather

on:
  push:
    paths:
      - 'applications/DotnetWeather/**'
      - '.github/workflows/dotnet-weather.yml'
  workflow_dispatch:

jobs:
  test:
    name: Perform the tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./applications/DotnetWeather

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  build-and-push-image:
    name: Push Docker image to Github Container registry
    runs-on: ubuntu-latest
#    needs: test
    defaults:
      run:
        working-directory: ./applications/DotnetWeather

    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/dotnet-weather

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
